# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart CI with Coverage

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests with coverage
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
          flutter test --coverage
          genhtml coverage/lcov.info --output-directory coverage/html

      - name: Check coverage percentage
        run: |
          total_lines=$(grep -Po 'LF:\d+' coverage/lcov.info | awk -F: '{s+=$2} END {print s}')
          covered_lines=$(grep -Po 'LH:\d+' coverage/lcov.info | awk -F: '{s+=$2} END {print s}')
          if [ "$total_lines" -eq 0 ]; then
            coverage=0
          else
            coverage=$(awk "BEGIN {printf \"%.2f\", ($covered_lines/$total_lines)*100}")
          fi
          echo "Coverage: $coverage%"
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Test coverage is below 80% ($coverage%)" && exit 1
          fi
        shell: bash
